services:
  - type: web
    name: t1allstars-frontend
    runtime: node
    region: frankfurt
    rootDir: tyler1-allstars
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://t1allstarsbackend.onrender.com/api
